# Generated by Django 4.2.23 on 2025-11-06 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="new_arrival",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["new_arrival", "-created_at"],
                name="api_product_new_arr_ab20d4_idx",
            ),
        ),
    ]
