# Generated by Django 4.2.23 on 2025-11-08 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_category_hierarchical_collections"),
    ]

    operations = [
        migrations.DeleteModel(name="ProductReview",),
    ]
